#!/bin/bash
boost_version=$(grep 'define.*BOOST_LIB_VERSION' ../../boost/version.hpp | sed 's/.*"\([^"]*\)".*/\1/')
echo Boost version tag = $boost_version
(cd ../../libs/accumulators/doc && bjam -a) 2>&1 | tee build.log
(cd ../../libs/geometry/doc/src/docutils/tools/doxygen_xml2qbk && bjam release) 2>&1 | tee -a build.log
cp ../../dist/bin/doxygen_xml2qbk* /usr/local/bin
(cd ../../libs/geometry/doc && ./make_qbk.py) 2>&1 | tee -a build.log
bjam -a --enable-index pdf xsl:param=fop1.extensions=0 xsl:param=xep.extensions=1 2>&1 | tee -a build.log
mkdir boost_${boost_version}_pdf
mv *.pdf boost_${boost_version}_pdf










