name: Release

on:
  push:
    tags:
      - boost-*

jobs:
  release-posix-cmake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.ref_name }}
          submodules: true

      - name: Cleanup
        shell: bash
        run: |
          find ${{ github.ref_name }} -name ".git" -prune -exec rm -rf {} +

      - name: Create archives
        run: |
          tar -czf ${{ github.ref_name }}-cmake.tar.gz ${{ github.ref_name }}
          sha256sum ${{ github.ref_name }}-cmake.tar.gz > ${{ github.ref_name }}-cmake.tar.gz.sha256
          tar -cJf ${{ github.ref_name }}-cmake.tar.xz ${{ github.ref_name }}
          sha256sum ${{ github.ref_name }}-cmake.tar.xz > ${{ github.ref_name }}-cmake.tar.xz.sha256

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.ref_name }}-cmake.tar.gz
            ${{ github.ref_name }}-cmake.tar.gz.sha256
            ${{ github.ref_name }}-cmake.tar.xz
            ${{ github.ref_name }}-cmake.tar.xz.sha256

  release-windows-cmake:
    runs-on: windows-latest

    needs: release-posix-cmake

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.ref_name }}
          submodules: true

      - name: Cleanup
        shell: bash
        run: |
          find ${{ github.ref_name }} -name ".git" -prune -exec rm -rf {} +

      - name: Create archives
        shell: cmd
        run: |
          7z a ${{ github.ref_name }}-cmake.zip ${{ github.ref_name }}
          sha256sum ${{ github.ref_name }}-cmake.zip > ${{ github.ref_name }}-cmake.zip.sha256
          7z a ${{ github.ref_name }}-cmake.7z ${{ github.ref_name }}
          sha256sum ${{ github.ref_name }}-cmake.7z > ${{ github.ref_name }}-cmake.7z.sha256

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.ref_name }}-cmake.zip
            ${{ github.ref_name }}-cmake.zip.sha256
            ${{ github.ref_name }}-cmake.7z
            ${{ github.ref_name }}-cmake.7z.sha256

  release-posix-b2-nodocs:
    runs-on: ubuntu-latest

    needs: release-windows-cmake

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.ref_name }}
          submodules: true

      - name: Cleanup
        shell: bash
        run: |
          find ${{ github.ref_name }} -name ".git" -prune -exec rm -rf {} +

      - name: Move headers, remove docs
        shell: bash
        run: |
          cd ${{ github.ref_name }}
          cp -r libs/*/include/boost libs/numeric/*/include/boost .
          rm -rf libs/*/include libs/numeric/*/include
          rm -rf libs/*/doc libs/numeric/*/doc
          rm -f CMakeLists.txt

      - name: Create archives
        run: |
          tar -czf ${{ github.ref_name }}-b2-nodocs.tar.gz ${{ github.ref_name }}
          sha256sum ${{ github.ref_name }}-b2-nodocs.tar.gz > ${{ github.ref_name }}-b2-nodocs.tar.gz.sha256
          tar -cJf ${{ github.ref_name }}-b2-nodocs.tar.xz ${{ github.ref_name }}
          sha256sum ${{ github.ref_name }}-b2-nodocs.tar.xz > ${{ github.ref_name }}-b2-nodocs.tar.xz.sha256

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.ref_name }}-b2-nodocs.tar.gz
            ${{ github.ref_name }}-b2-nodocs.tar.gz.sha256
            ${{ github.ref_name }}-b2-nodocs.tar.xz
            ${{ github.ref_name }}-b2-nodocs.tar.xz.sha256

  release-windows-b2-nodocs:
    runs-on: windows-latest

    needs: release-posix-b2-nodocs

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.ref_name }}
          submodules: true

      - name: Cleanup
        shell: bash
        run: |
          find ${{ github.ref_name }} -name ".git" -prune -exec rm -rf {} +

      - name: Move headers, remove docs
        shell: bash
        run: |
          cd ${{ github.ref_name }}
          cp -r libs/*/include/boost libs/numeric/*/include/boost .
          rm -rf libs/*/include libs/numeric/*/include
          rm -rf libs/*/doc libs/numeric/*/doc
          rm -f CMakeLists.txt

      - name: Create archives
        shell: cmd
        run: |
          7z a ${{ github.ref_name }}-b2-nodocs.zip ${{ github.ref_name }}
          sha256sum ${{ github.ref_name }}-b2-nodocs.zip > ${{ github.ref_name }}-b2-nodocs.zip.sha256
          7z a ${{ github.ref_name }}-b2-nodocs.7z ${{ github.ref_name }}
          sha256sum ${{ github.ref_name }}-b2-nodocs.7z > ${{ github.ref_name }}-b2-nodocs.7z.sha256

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.ref_name }}-b2-nodocs.zip
            ${{ github.ref_name }}-b2-nodocs.zip.sha256
            ${{ github.ref_name }}-b2-nodocs.7z
            ${{ github.ref_name }}-b2-nodocs.7z.sha256
